[package]
name = "web_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "^0.12" }
scraper = "0.20"
tokio = { version = "1.40", features = ["full"] }
anyhow = "1.0"
chrono = "0.4"
url = "2"

[dev-dependencies]
wiremock = "0.6"
